import CookieBanner from './CookieBanner';

export function NitoLanding() {
 return <>

<header className="header"><nav className="wrap nav" aria-label="Navegación principal"><a className="brand" href="/" aria-label="Nito, inicio"><img src="/landing-assets/logo.jpeg" width="49" height="49" alt="Nito" />nito<span>Socios</span></a><div className="navlinks"><a href="#funciona">Cómo funciona</a><a href="#planes">Planes</a><a href="#preguntas">Preguntas</a></div><div className="actions"><a href="https://socios.nitoapp.online/login">Ingresar</a><a className="button dark" href="https://socios.nitoapp.online/login">Probar gratis <span aria-hidden="true">↗</span></a></div></nav></header>
<main><section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">Para quienes hacen crecer el deporte</span><h1>Tu gente, en marcha.<br /><em>Tus cuotas,<br />bajo control.</em></h1><p>Sabé quién pagó, qué cuotas están pendientes y a quién avisar. Organizá la administración de tu club, gimnasio o academia en un solo lugar.</p><div className="actions"><a className="button" href="https://socios.nitoapp.online/login">Probar Nito Socios <span aria-hidden="true">↗</span></a><a className="button outline" href="#funciona">Conocer cómo funciona</a></div><div className="trust"><span>30 días gratis</span><span>Sin tarjeta de crédito</span></div></div><div className="photo"><img src="/landing-assets/club.png" alt="Una jornada deportiva con familias y chicos en un club" width="640" height="640" fetchPriority="high" /><span className="photo-caption">Más tiempo para tu comunidad.</span><div className="photo-card"><strong>El club sigue. La administración también.</strong><p>Socios, pagos y pendientes ordenados, para que cada consulta tenga una respuesta.</p></div></div></div></section>
<div className="wrap audiences"><span>Un lugar para cada equipo.</span><span>Clubes deportivos</span><span>Gimnasios</span><span>Academias</span><span>Personal trainers</span></div>
<section className="section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">Menos vueltas. Más claridad.</span><h2>Que cobrar la cuota<br />no te ocupe todo el día.</h2></div><p>La información que necesitás para administrar, sin buscar entre planillas y conversaciones.</p></div><div className="cards"><article className="card"><span className="number">01 / SOCIOS</span><h3>Cada socio, con su información.</h3><p>Consultá los datos y el estado de cada miembro desde un mismo lugar. Mantené tu padrón organizado.</p></article><article className="card"><span className="number">02 / PAGOS</span><h3>Lo cobrado y lo pendiente, a la vista.</h3><p>Registrá pagos y revisá las cuotas pendientes para saber dónde concentrar el seguimiento.</p></article><article className="card"><span className="number">03 / SEGUIMIENTO</span><h3>El recordatorio, listo para enviar.</h3><p>Abrí WhatsApp con el mensaje preparado. Revisalo y envialo vos, con el trato de siempre.</p></article></div></div></section>
<section className="section white" id="funciona"><div className="wrap flow"><div><span className="eyebrow">Así entra Nito en tu día</span><h2>De “¿ya pagó?”<br />a tenerlo claro.</h2><p>Un recorrido simple para empezar a ordenar tus cobros.</p><div className="flow-list"><div className="flow-item"><b>1</b><div><strong>Creá tu cuenta y cargá tus socios.</strong><p>Empezá con la información de tu club o actividad.</p></div></div><div className="flow-item"><b>2</b><div><strong>Registrá los pagos.</strong><p>Consultá el estado de cuenta de cada socio.</p></div></div><div className="flow-item"><b>3</b><div><strong>Seguí los pendientes.</strong><p>Prepará los avisos y envialos por WhatsApp.</p></div></div></div></div><div className="example" aria-label="Ejemplo ilustrativo de organización de cuotas"><div className="example-head"><strong>Cuotas de septiembre</strong><span>Ejemplo ilustrativo</span></div><div className="balances"><div className="balance"><small>Cuotas pagadas</small><strong>42</strong></div><div className="balance pending"><small>Por cobrar</small><strong>8</strong></div></div><div className="member"><span className="avatar">LM</span><span>Lucía Martínez</span><span className="status">Al día</span></div><div className="member"><span className="avatar">TG</span><span>Tomás García</span><span className="status due">Pendiente</span></div><div className="member"><span className="avatar">SP</span><span>Sofía Pérez</span><span className="status">Al día</span></div><p className="sample-note">Datos ficticios para mostrar el uso. No es una captura de la aplicación.</p></div></div></section>
<section className="section" id="planes"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">Elegí según tu actividad</span><h2>Empezá por probarlo.<br />Después elegí tu plan.</h2></div><p>30 días de prueba sin tarjeta. Conocé la herramienta antes de decidir.</p></div><div className="cards"><article className="card price"><h3>Trainer</h3><p>Para tu grupo de alumnos.</p><div className="amount">$12.000</div><span className="period">ARS por mes</span><ul><li>Hasta 20 alumnos o socios</li><li>Gestión de cobros</li><li>Integración con Mercado Pago</li><li>No incluye reservas</li></ul><a className="button dark" href="https://socios.nitoapp.online/login">Probar gratis</a></article><article className="card price highlight"><span className="tag">Para academias</span><h3>Estudio</h3><p>Para organizar una actividad que crece.</p><div className="amount">$24.000</div><span className="period">ARS por mes</span><ul><li>Hasta 200 alumnos o socios</li><li>Personalización con tu logo</li><li>Sistema de reservas</li><li>Reportes avanzados</li><li>Soporte prioritario</li></ul><a className="button" href="https://socios.nitoapp.online/login">Probar gratis</a></article><article className="card price"><h3>Club</h3><p>Para la gestión de tu institución.</p><div className="amount">$45.000</div><span className="period">ARS por mes</span><ul><li>Alumnos o socios ilimitados</li><li>Todo lo incluido en Estudio</li><li>Recepción y torneos</li><li>Soporte VIP</li></ul><a className="button dark" href="https://socios.nitoapp.online/login">Probar gratis</a></article></div><p className="pricing-note">¿Querés consultar qué plan se adapta a tu club? <a className="text-link" href="https://wa.me/5491155144268?text=Hola%2C%20quiero%20conocer%20Nito%20Socios%20y%20consultar%20qu%C3%A9%20plan%20me%20conviene.">Hablá con nosotros</a></p></div></section>
<section className="section white" id="preguntas"><div className="wrap faq"><div><span className="eyebrow">Antes de empezar</span><h2>Las dudas<br />más comunes.</h2><p>Y si te queda alguna, estamos del otro lado.</p></div><div><details><summary>¿Cómo empiezo la prueba?</summary><p>Entrá desde “Probar gratis” y elegí “Regístrate” en la pantalla de acceso. Completá tus datos y creá tu cuenta. La prueba publicada es de 30 días y no requiere tarjeta.</p></details><details><summary>¿Sirve si tengo pocos alumnos?</summary><p>Sí. El plan Trainer contempla hasta 20 alumnos o socios. Para grupos más grandes, podés consultar Estudio y Club.</p></details><details><summary>¿Los WhatsApp se envían solos?</summary><p>No. Nito abre WhatsApp con el texto preparado. Vos revisás el mensaje y decidís enviarlo.</p></details><details><summary>¿Puedo usar reservas?</summary><p>El sistema de reservas está incluido desde el plan Estudio. El plan Trainer se concentra en alumnos y cobros.</p></details><details><summary>¿Ya tengo cuenta?</summary><p><a className="text-link" href="https://socios.nitoapp.online/login">Ingresá a tu panel</a> con tus credenciales habituales.</p></details></div></div></section>
<section className="section"><div className="wrap closing"><div><span className="eyebrow">Tu próximo paso</span><h2>Probalo con tu actividad.<br />Decidí con experiencia.</h2><p>Creá tu cuenta desde “Regístrate” en la pantalla de acceso.</p></div><a className="button" href="https://socios.nitoapp.online/login">Empezar mi prueba gratis <span aria-hidden="true">↗</span></a></div></section></main>
<footer className="footer"><div className="wrap footer-row"><a className="brand" href="/">nito<span>Socios</span></a><div className="footer-links"><a href="/">Inicio</a><a href="https://socios.nitoapp.online/legal/terminos-condiciones.pdf">Términos</a><a href="https://socios.nitoapp.online/legal/politica-privacidad.pdf">Privacidad</a></div><small>© 2026 Nito Socios</small></div></footer>
<CookieBanner />
</>;
}
